### ISSUE TITLE
jhmdb acc?

### ISSUE THREAD

**Issue by zgs731** [fandulu/DD-Net#11]
How do you train, so that the network accuracy rate is above 77%, and the network I train is only about 70%.  The data set is 21 categories, not 14 categories.
I hope you can explain the training method.

**Comment by fandulu** [comment]
Plz clone this code and run, I forget to fix a bug on colab, sorry for it. 

Update: I fixed the bug on colab now, could you try it again?
Besides, anhminh3105  uses this code to pulls val_acc of each split over 80% on JHMDB with the weighted class to alleviate the skewed effect since 'walk' has ~3 times more data compared to others.

**Comment by zgs731** [comment]
Thank you for your work！@fandulu 
I got the accuracy close to you at colab.
I want to try anhminh3105's work,but I didn't find his code. and 'walk' has only 41 segments,basically consistent with other classes.

**Comment by fandulu** [comment]
@zgs731 , yes, I checked as the sample number is as follows, anhminh3105 may use this model on his own data and I misunderstood it, sorry for the misleading comments.
brush_hair:41
catch:48
clap:44
climb_stairs:40
golf:42
jump:39
kick_ball:36
pick:40
pour:55
pullup:55
push:42
run:40
shoot_ball:40
shoot_bow:53
shoot_gun:55
sit:39
stand:36
swing_baseball:54
throw:46
walk:41
wave:42

**Comment by anhminh3105** [comment]
Hi @fandulu and @zgs731.

It was my mistake to say that class 'walk' has 3 times more data in JHMDB as it was the case only for the HMDB dataset of which the JHMDB is a subset and I was looking over the HMDB [homepage](http://serre-lab.clps.brown.edu/resource/hmdb-a-large-human-motion-database/) and was referencing it over based on this image.
![img](http://serre-lab.clps.brown.edu/wp-content/uploads/2012/08/ActionCategories.jpg)

I just also uploaded my variation to github and if you would like to check it out, please find it [here](https://github.com/anhminh3105/DD-Net/tree/master/JHMDB). Just to justify how I got val_acc  above 80%, it was because I only trained the model on a subset of JHMDB dataset with added weighted class training. Specifically, the dataset subset contained only specified classes (e.g. walk, sit, catch, etc.) that I could easily test it using Openpose using input from camera with myself.

Br.

**Comment by fandulu** [comment]
Hi, anhminh3105, thanks very much for offering these comments!
